name: DSM diy

on: workflow_dispatch

jobs:
  redpill:
    runs-on: ubuntu-latest
    name: Build RedPill lkm and load
    steps:
     
      - name: Build DS918+ 7.0.1
        id: build-ds918-70
        run: |
            bash build-ds918-7.0.1.sh
    
      - name: Archive DS918+ 7.0.1 loader image
        uses: actions/upload-artifact@v2
        with:
          name: redpill-DS918+_7.0.1-loader
          path: output/redpill-DS918+_7.0*.img
